server:
  port: 9009
spring:
  application:
    name: tensquare-sms #指定服务名
  rabbitmq:
    host: 192.168.246.128
aliyun:
  sms:
    accessKeyId: 11
    accessKeySecret: 22
    template_code: 33
    sign_name: 44
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
