server:
  port: 12000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/Novalife/tensquare-config.git
  rabbitmq:
    host: 192.168.246.128
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh